# Generated by Django 4.1.3 on 2022-12-04 12:37

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('location', models.CharField(choices=[('M', 'Muharraq'), ('S', 'Seef')], default='M', max_length=1)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('user_code', models.IntegerField()),
                ('image', models.CharField(default='image not available', max_length=800)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
                ('trainer', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('M', 'Muharraq'), ('S', 'Seef')], default='M', max_length=1)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=2)),
                ('time', models.TimeField(verbose_name='Start Time')),
                ('duration', models.CharField(max_length=100)),
                ('seats', models.IntegerField(verbose_name='Total Seats')),
                ('memberships', models.ManyToManyField(to='main_app.membership')),
            ],
        ),
    ]
