# Generated by Django 4.1.3 on 2022-12-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='credit',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
    ]
