# Generated by Django 4.1.3 on 2022-12-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_membership_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='memberships',
        ),
        migrations.AddField(
            model_name='membership',
            name='classes',
            field=models.ManyToManyField(to='main_app.class'),
        ),
    ]
