# Generated by Django 4.1.3 on 2022-12-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_class_memberships_membership_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='classes',
            field=models.ManyToManyField(blank=True, to='main_app.class'),
        ),
    ]
