# Generated by Django 4.1.3 on 2022-12-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_membership_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='credit',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='image',
            field=models.CharField(blank=True, default='image not available', max_length=800),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user_code',
            field=models.IntegerField(blank=True),
        ),
    ]
